plugins {
    id 'java'
    id 'war'
    id 'org.hidetake.ssh' version '2.11.2'
}

apply plugin: 'org.hidetake.ssh'

remotes {
    host {
        host = '...'
        user = 'root'
        password = '...'
    }
}

ssh.settings {
    knownHosts = allowAnyHosts
}

group 'com.thomas'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()  // Maven Central mặc định
    maven { url "https://repo1.maven.org/maven2" }  // Thêm kho Maven chính thức
    maven { url "https://mvnrepository.com/artifact/jstl/jstl" }  // Thêm repo từ mvnrepository
}

ext {
    junitVersion = '5.11.0'
}

sourceCompatibility = '21'
targetCompatibility = '21'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'

    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
    implementation 'org.jdbi:jdbi3-core:3.25.0'  // Thêm phiên bản tương ứng nếu cần
    implementation 'javax.mail:javax.mail-api:1.6.2'
    implementation 'org.json:json:20210307'
    implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    implementation 'com.google.code.gson:gson:2.8.8'
    implementation 'mysql:mysql-connector-java:8.0.30'
    implementation 'jstl:jstl:1.2'
}

test {
    useJUnitPlatform()
}
task docker_app_start {
    doLast {
        println 'begin docker_app_start'

        ssh.run {
            session(remotes.host) {
                execute 'docker stop tomcat9', ignoreError: true
                execute '''
                    docker run -it --rm -d \
                    --name tomcat9 \
                    -v /usr/deploy:/usr/local/tomcat/webapps \
                    -p 80:8080 \
                    tomcat:9.0
                '''
            }
        }
    }
}

task docker_upload_file_to_server {
    doLast {
        println 'begin docker_upload_file_to_server'
        ssh.run {
            session(remotes.host) {
                remove '/usr/deploy/lab.war'
                remove '/usr/deploy/lab/'
                remove '/usr/deploy/lab5-1/'
                put from: "${project.projectDir}/build/libs/demo-1.0-SNAPSHOT.war",
                        into: "/usr/deploy/lab.war"
            }
        }
    }
}

task docker_deploy {
    dependsOn build
    dependsOn docker_upload_file_to_server
    dependsOn docker_app_start

    // Đảm bảo upload xong mới chạy docker
    tasks.docker_app_start.mustRunAfter docker_upload_file_to_server
}